// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go_learning/todolist/internal/server"
	"go_learning/todolist/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeServer 初始化服务
func InitializeServer(db *gorm.DB) (*server.Server, error) {
	userService := service.NewUserService(db)
	userHandler := server.NewUserHandler(userService)
	fileService := service.NewFileService(db)
	fileHandler := server.NewFileHandler(fileService)
	serverServer := server.NewServer(userHandler, fileHandler)
	return serverServer, nil
}
